window.quizData = {
  "title": "PHY 121 - Electricity & Magnetism",
  "questions": [
    // --- Segment 1: Electrostatics & Coulomb's Law (Questions 1-50) ---
    // Basic Concepts (1-10)
    { "question": "What is the study of electric charges at rest called?", "options": ["Current electricity", "Magnetism", "Electrostatics", "Vector analysis"], "answer": "Electrostatics" },
    { "question": "What is the S.I. unit of electric charge?", "options": ["Newton (N)", "Joule (J)", "Watt (W)", "Coulomb (C)"], "answer": "Coulomb (C)" },
    { "question": "Who discovered electric charges and suggested the names for their types?", "options": ["Isaac Newton", "Charles-Augustine de Coulomb", "Michael Faraday", "Benjamin Franklin"], "answer": "Benjamin Franklin" },
    { "question": "What is the fundamental law of electrostatics?", "options": ["Like charges attract, unlike charges repel", "Like charges repel, unlike charges attract", "All charges repel each other", "All charges attract each other"], "answer": "Like charges repel, unlike charges attract" },
    { "question": "A glass rod rubbed with silk acquires what type of charge?", "options": ["Negative charge", "Positive charge", "No charge", "Both positive and negative charges"], "answer": "Positive charge" },
    { "question": "A rubber or ebonite rod rubbed with fur acquires what type of charge?", "options": ["Negative charge", "Positive charge", "No charge", "Both positive and negative charges"], "answer": "Negative charge" },
    { "question": "In an isolated system, electric charge is always...", "options": ["Created", "Destroyed", "Changing", "Conserved"], "answer": "Conserved" },
    { "question": "During the process of rubbing, which particles are transferred from one object to another?", "options": ["Protons", "Neutrons", "Electrons", "Nuclei"], "answer": "Electrons" },
    { "question": "The study of electric charges in motion is called...?", "options": ["Electrostatics", "Static electricity", "Current electricity", "Electromagnetism"], "answer": "Current electricity" },
    { "question": "An object that loses electrons becomes...", "options": ["Negatively charged", "Positively charged", "Neutrally charged", "An insulator"], "answer": "Positively charged" },
    
    // Methods of Charging & Conductors (11-25)
    { "question": "Which method of producing charge involves rubbing two objects against each other?", "options": ["By induction", "By conduction", "By friction", "By polarization"], "answer": "By friction" },
    { "question": "When an uncharged conductor is touched by a charged object, it becomes charged by...", "options": ["Induction", "Friction", "Contact or conduction", "Radiation"], "answer": "Contact or conduction" },
    { "question": "Charging by induction involves bringing a charged object ____ to an uncharged object, without touching it.", "options": ["in contact with", "far away from", "close", "parallel"], "answer": "close" },
    { "question": "What is an electroscope used for?", "options": ["To measure current", "To create electric charge", "To detect the presence of electric charge", "To measure voltage"], "answer": "To detect the presence of electric charge" },
    { "question": "In a gold-leaf electroscope, when a charged object is brought near the metal disc, the leaves...", "options": ["Come closer together", "Do nothing", "Vibrate", "Diverge or spread apart"], "answer": "Diverge or spread apart" },
    { "question": "Materials that allow easy flow of electric charges are called...?", "options": ["Insulators", "Semiconductors", "Conductors", "Resistors"], "answer": "Conductors" },
    { "question": "Which of the following is an example of a conductor?", "options": ["Glass", "Rubber", "Dry wood", "Metallic copper"], "answer": "Metallic copper" },
    { "question": "Materials that do not allow the flow of electric charges are called...?", "options": ["Conductors", "Superconductors", "Semiconductors", "Insulators"], "answer": "Insulators" },
    { "question": "Which of the following is an example of an insulator?", "options": ["Aluminium", "Silver", "Salt solution", "Plastic"], "answer": "Plastic" },
    { "question": "Materials whose ability to conduct electricity is between that of conductors and insulators are known as...?", "options": ["Resistors", "Capacitors", "Semiconductors", "Superconductors"], "answer": "Semiconductors" },
    { "question": "If a negatively charged object is brought near a negatively charged electroscope, the divergence of the leaves will...", "options": ["Decrease", "Increase", "Stay the same", "Collapse completely"], "answer": "Increase" },
    { "question": "If a positively charged object is brought near a negatively charged electroscope, the divergence of the leaves will...", "options": ["Decrease", "Increase", "Stay the same", "Vibrate"], "answer": "Decrease" },
    { "question": "Germanium and silicon are examples of...?", "options": ["Conductors", "Insulators", "Semiconductors", "Alloys"], "answer": "Semiconductors" },
    { "question": "In charging by conduction, the charge transferred to the uncharged object is ____ the charge on the charging object.", "options": ["the same type as", "opposite to", "unrelated to", "greater than"], "answer": "the same type as" },
    { "question": "The process of connecting a charged body to the earth to neutralize it is called...?", "options": ["Induction", "Conduction", "Polarization", "Earthing"], "answer": "Earthing" },
    
    // Coulomb's Law (26-50)
    { "question": "Coulomb's Law describes the magnitude of the...", "options": ["Gravitational force", "Magnetic force", "Electrostatic force", "Nuclear force"], "answer": "Electrostatic force" },
    { "question": "According to Coulomb's Law, the electrostatic force is directly proportional to the...", "options": ["Distance between the charges", "Square of the distance between charges", "Sum of the charges", "Product of the charges"], "answer": "Product of the charges" },
    { "question": "The electrostatic force is inversely proportional to the...", "options": ["Product of the charges", "Distance between the charges", "Square of the distance between charges", "Sum of the charges"], "answer": "Square of the distance between charges" },
    { "question": "If the distance between two charges is doubled, the force between them is reduced by a factor of...", "options": ["1/2", "2", "1/4", "4"], "answer": "1/4" },
    { "question": "If the distance between two charges is halved, the force between them is increased by a factor of...", "options": ["1/2", "2", "1/4", "4"], "answer": "4" },
    { "question": "The constant 'k' in Coulomb's Law is approximately equal to...", "options": ["9.0 x 10^9 Nm^2/C^2", "8.854 x 10^-12 C^2/Nm^2", "1.602 x 10^-19 C", "6.67 x 10^-11 Nm^2/kg^2"], "answer": "9.0 x 10^9 Nm^2/C^2" },
    { "question": "What is the nature of the force between a -4 µC charge and a +7 µC charge?", "options": ["Repulsive", "Attractive", "Zero", "It cannot be determined"], "answer": "Attractive" },
    { "question": "What is the nature of the force between two positive charges?", "options": ["Repulsive", "Attractive", "Zero", "It depends on the distance"], "answer": "Repulsive" },
    { "question": "The constant ε₀ is known as the...", "options": ["Permeability of free space", "Permittivity of free space", "Coulomb's constant", "Charge of an electron"], "answer": "Permittivity of free space" },
    { "question": "Coulomb's law is an example of an...", "options": ["Inverse square law", "Direct proportion law", "Linear law", "Exponential law"], "answer": "Inverse square law" },
    { "question": "A charged object can exert an attractive force on an uncharged object due to...", "options": ["Conduction", "Friction", "Induced-charge effect (polarization)", "Gravity"], "answer": "Induced-charge effect (polarization)" },
    { "question": "Electrostatic force is what type of physical quantity?", "options": ["Scalar", "Vector", "Constant", "Dimensionless"], "answer": "Vector" },
    { "question": "The direction of the electrostatic force is always...", "options": ["Perpendicular to the line joining the charges", "Along the line joining the two charges", "In the direction of the larger charge", "In the direction of the smaller charge"], "answer": "Along the line joining the two charges" },
    { "question": "Coulomb's Law obeys which of Newton's Laws?", "options": ["First Law", "Second Law", "Third Law", "Law of Gravitation"], "answer": "Third Law" },
    { "question": "One microcoulomb (µC) is equal to...", "options": ["10^-3 C", "10^-6 C", "10^-9 C", "10^-12 C"], "answer": "10^-6 C" },
    { "question": "One nanocoulomb (nC) is equal to...", "options": ["10^-3 C", "10^-6 C", "10^-9 C", "10^-12 C"], "answer": "10^-9 C" },
    { "question": "In the formula F = k * q1*q2 / r^2, what does 'r' represent?", "options": ["The radius of the charges", "The resistance", "The distance between the charges", "The repulsive factor"], "answer": "The distance between the charges" },
    { "question": "Calculate the force between two equal charges of 3 nC at 50 cm apart. (k = 9x10^9)", "options": ["3.24 x 10^-7 N", "1.62 x 10^-7 N", "6.48 x 10^-8 N", "8.1 x 10^-8 N"], "answer": "3.24 x 10^-7 N" },
    { "question": "Two charges, -4 µC and +7 µC, are 12 cm apart. The magnitude of the force is...", "options": ["1.75 N", "17.5 N", "175 N", "0.175 N"], "answer": "17.5 N" },
    { "question": "If you double one of the charges in a two-charge system, what happens to the force?", "options": ["It is halved", "It is doubled", "It is quadrupled", "It stays the same"], "answer": "It is doubled" },
    { "question": "The symbol 'q' or 'Q' is used to denote...", "options": ["Force", "Distance", "Electric Charge", "Electric Field"], "answer": "Electric Charge" },
    { "question": "The force that charge q1 exerts on q2 is ____ in magnitude but opposite in direction to the force that q2 exerts on q1.", "options": ["different", "half", "double", "equal"], "answer": "equal" },
    { "question": "To solve numerical problems with Coulomb's law, all units must be expressed in...", "options": ["CGS units", "Imperial units", "S.I. units", "Any units will work"], "answer": "S.I. units" },
    { "question": "A force of 0.15 N exists between charges 1 µC and 5 µC. What is the distance between them? (k = 9x10^9)", "options": ["0.3 m", "0.55 m", "3 m", "0.09 m"], "answer": "0.3 m" },
    { "question": "What is the charge of a single electron or proton (magnitude)?", "options": ["1.602 x 10^-19 C", "9.11 x 10^-31 C", "1 C", "9.0 x 10^9 C"], "answer": "1.602 x 10^-19 C" },
    
    // --- Segment 2: Superposition & Electric Fields (Questions 51-100) ---
    // Principle of Superposition (51-60)
    { "question": "The principle of superposition is used to find the total electric force when a system has...", "options": ["Only one charge", "Only two charges", "More than two charges", "No charges"], "answer": "More than two charges" },
    { "question": "The total force on any one charge in a multi-charge system is the ____ of the forces from the other charges.", "options": ["vector sum", "scalar sum", "product", "difference"], "answer": "vector sum" },
    { "question": "In a three-charge system (q1, q2, q3), the total force F1 on charge q1 is given by...", "options": ["F1 = F21 + F31", "F1 = F12 * F13", "F1 = F12 + F13", "F1 = F23 + F32"], "answer": "F1 = F12 + F13" },
    { "question": "When charges are arranged in a non-linear configuration (like a triangle), what mathematical theorem is often used to find the magnitude of the total force?", "options": ["Binomial Theorem", "Pythagoras Theorem", "Calculus Fundamental Theorem", "Superposition Theorem"], "answer": "Pythagoras Theorem" },
    { "question": "Finding the total force on a charge in a multi-charge system requires careful attention to the configuration, signs of the charges, and...?", "options": ["Temperature", "Pressure", "Direction of the force", "Time"], "answer": "Direction of the force" },
    { "question": "In Case 1 from the notes, with three charges in a line, the force F13 on q1 due to q3 depends on the distance...", "options": ["x", "y", "z = x + y", "x - y"], "answer": "z = x + y" },
    { "question": "Vector component resolution is necessary when forces are not acting along the same...", "options": ["plane", "charge", "time", "line"], "answer": "line" },
    { "question": "In Case 2 from the notes (a right-angle triangle), the total force on q1 is found using F1 = sqrt(F12^2 + F13^2). This is an application of...?", "options": ["Coulomb's Law only", "Pythagoras relation", "Newton's First Law", "Ohm's Law"], "answer": "Pythagoras relation" },
    { "question": "The principle of superposition assumes that the force between any two charges is ____ by the presence of other charges.", "options": ["greatly affected", "unaffected", "cancelled out", "doubled"], "answer": "unaffected" },
    { "question": "For a system of 'n' charges, the total force on charge q1 is the sum of forces F12, F13, F14, ... up to...?", "options": ["F1(n-1)", "F(n-1)n", "F1n", "Fnn"], "answer": "F1n" },
    
    // Electric Fields (61-85)
    { "question": "An electric field is said to exist at a point where a ____ experiences an electric force.", "options": ["Neutron", "Test charge", "Magnet", "Wire"], "answer": "Test charge" },
    { "question": "Electric field (E) is defined as the...", "options": ["Force per unit test charge", "Charge per unit force", "Total charge in a region", "Total force in a region"], "answer": "Force per unit test charge" },
    { "question": "What is the S.I. unit of electric field strength?", "options": ["Coulomb (C)", "Newton (N)", "Newton per Coulomb (N/C)", "Coulomb per Newton (C/N)"], "answer": "Newton per Coulomb (N/C)" },
    { "question": "For a positive test charge, the direction of the electric field is ____ the direction of the force.", "options": ["opposite to", "perpendicular to", "the same as", "unrelated to"], "answer": "the same as" },
    { "question": "For a negative test charge, the direction of the electric field is ____ the direction of the force.", "options": ["opposite to", "perpendicular to", "the same as", "unrelated to"], "answer": "opposite to" },
    { "question": "The electric field due to a single point charge 'q' is given by the formula...", "options": ["E = kq/r", "E = kqr", "E = kq/r^2", "E = k/r^2"], "answer": "E = kq/r^2" },
    { "question": "As you move farther away from a point charge, the electric field strength...", "options": ["Increases", "Decreases", "Stays the same", "Becomes zero instantly"], "answer": "Decreases" },
    { "question": "Calculate the electric field strength at 2.0m from a point charge of 4µC. (k=9x10^9)", "options": ["9000 N/C", "18000 N/C", "4500 N/C", "36000 N/C"], "answer": "9000 N/C" },
    { "question": "The formula F = qE relates the force (F) on a charge 'q' to the...", "options": ["Electric potential", "Electric field strength (E)", "Distance", "Coulomb's constant"], "answer": "Electric field strength (E)" },
    { "question": "Like the electrostatic force, the electric field is a ____ quantity.", "options": ["scalar", "vector", "constant", "base"], "answer": "vector" },
    { "question": "The principle of superposition also applies to...", "options": ["Temperature", "Mass", "Electric fields", "Time"], "answer": "Electric fields" },
    { "question": "The total electric field at a point due to multiple charges is the ____ of the individual fields at that point.", "options": ["vector sum", "scalar sum", "product", "average"], "answer": "vector sum" },
    { "question": "If an electric field of 11.2 N/C is due to a charge q, and a force of 1.7 N is felt, what is the value of q?", "options": ["0.15 C", "6.58 C", "18.04 C", "1.7 C"], "answer": "0.15 C" },
    { "question": "What is an electric dipole?", "options": ["A single isolated charge", "A pair of equal and opposite point charges separated by a distance", "A pair of equal and like point charges", "Any two charges in a system"], "answer": "A pair of equal and opposite point charges separated by a distance" },
    { "question": "The total force on an electric dipole in a uniform external electric field is...", "options": ["Double the force on one charge", "Zero", "Infinite", "Dependent on the field strength"], "answer": "Zero" },
    { "question": "Electric dipole moment (p) is defined as the product of the charge (q) and the...", "options": ["Electric field", "Force", "Distance of separation (d)", "Torque"], "answer": "Distance of separation (d)" },
    { "question": "What is the S.I. unit for electric dipole moment?", "options": ["Newton meter (Nm)", "Coulomb per meter (C/m)", "Coulomb meter (Cm)", "Newton per Coulomb (N/C)"], "answer": "Coulomb meter (Cm)" },
    { "question": "The direction of the electric dipole moment vector is from the...", "options": ["Positive charge to the negative charge", "Negative charge to the positive charge", "Center to the positive charge", "Center to the negative charge"], "answer": "Negative charge to the positive charge" },
    { "question": "An electric dipole in an external electric field experiences a force that tends to rotate it. This force is called...", "options": ["Momentum", "Inertia", "Centripetal force", "Torque"], "answer": "Torque" },
    { "question": "The torque on a dipole is given by T = pEsin(θ). What does θ represent?", "options": ["The charge", "The angle between p and E", "The distance", "The temperature"], "answer": "The angle between p and E" },
    { "question": "Lines of force are used to represent...", "options": ["Electric current", "Electric field patterns", "Magnetic fields", "Voltage levels"], "answer": "Electric field patterns" },
    { "question": "A key property of electric field lines is that they...", "options": ["Cross each other frequently", "Form closed loops", "Do not cross or intersect each other", "Are always circles"], "answer": "Do not cross or intersect each other" },
    { "question": "For an isolated positive charge, the electric field lines are directed...", "options": ["Radially inward", "Radially outward", "In a circle", "Parallel to the charge"], "answer": "Radially outward" },
    { "question": "For an isolated negative charge, the electric field lines are directed...", "options": ["Radially inward", "Radially outward", "In a circle", "Away from the charge"], "answer": "Radially inward" },
    { "question": "The region between two like charges where the electric field is zero is called the...", "options": ["Equilibrium point", "Neutral point", "Dipole center", "Superposition point"], "answer": "Neutral point" }
  ]
};